export const Tools = {
  SELECT: 0,
  TEXT: 1,
  RECTANGLE: 2,
  IMAGE: 3,
  MARQUEE: 4,
  FULLSCREEN: 5,
  LAYER: 6,
};

export const ToolsAttributes = {
  ICONSIZE: 30,
  ADJICONSIZE: 30,
  TEXTCOLOR: "text-white",
  COLOR: "#000",
  TEXTWIDTH: 230,
  TEXTHEIGHT: 49,
  INITFONTSIZE: 40,
  IMGWIDTH: 200,
  BACKGROUNDCOLOR: "#ff0000",
  MARQUEETEXT: "EXAMPLE EXAMPLE EXAMPLE",
  TEXT: "YOUR TEXT",
  LINEHEIGHT: 1,
  FONTWEIGHT: "bold",
};
